import 'package:islami_app/models/sura_data_model.dart';

abstract class Constants {
  List<String> arabicQuranSuraNames = [
    "الفاتحه",
    "البقرة",
    "آل عمران",
    "النساء",
    "المائدة",
    "الأنعام",
    "الأعراف",
    "الأنفال",
    "التوبة",
    "يونس",
    "هود",
    "يوسف",
    "الرعد",
    "إبراهيم",
    "الحجر",
    "النحل",
    "الإسراء",
    "الكهف",
    "مريم",
    "طه",
    "الأنبياء",
    "الحج",
    "المؤمنون",
    "النّور",
    "الفرقان",
    "الشعراء",
    "النّمل",
    "القصص",
    "العنكبوت",
    "الرّوم",
    "لقمان",
    "السجدة",
    "الأحزاب",
    "سبأ",
    "فاطر",
    "يس",
    "الصافات",
    "ص",
    "الزمر",
    "غافر",
    "فصّلت",
    "الشورى",
    "الزخرف",
    "الدّخان",
    "الجاثية",
    "الأحقاف",
    "محمد",
    "الفتح",
    "الحجرات",
    "ق",
    "الذاريات",
    "الطور",
    "النجم",
    "القمر",
    "الرحمن",
    "الواقعة",
    "الحديد",
    "المجادلة",
    "الحشر",
    "الممتحنة",
    "الصف",
    "الجمعة",
    "المنافقون",
    "التغابن",
    "الطلاق",
    "التحريم",
    "الملك",
    "القلم",
    "الحاقة",
    "المعارج",
    "نوح",
    "الجن",
    "المزّمّل",
    "المدّثر",
    "القيامة",
    "الإنسان",
    "المرسلات",
    "النبأ",
    "النازعات",
    "عبس",
    "التكوير",
    "الإنفطار",
    "المطفّفين",
    "الإنشقاق",
    "البروج",
    "الطارق",
    "الأعلى",
    "الغاشية",
    "الفجر",
    "البلد",
    "الشمس",
    "الليل",
    "الضحى",
    "الشرح",
    "التين",
    "العلق",
    "القدر",
    "البينة",
    "الزلزلة",
    "العاديات",
    "القارعة",
    "التكاثر",
    "العصر",
    "الهمزة",
    "الفيل",
    "قريش",
    "الماعون",
    "الكوثر",
    "الكافرون",
    "النصر",
    "المسد",
    "الإخلاص",
    "الفلق",
    "الناس",
  ];
  List<String> englishQuranSuraNames = [
    "Al-Fatiha",
    "Al-Baqarah",
    "Aal-E-Imran",
    "An-Nisa'",
    "Al-Ma'idah",
    "Al-An'am",
    "Al-A'raf",
    "Al-Anfal",
    "At-Tawbah",
    "Yunus",
    "Hud",
    "Yusuf",
    "Ar-Ra'd",
    "Ibrahim",
    "Al-Hijr",
    "An-Nahl",
    "Al-Isra",
    "Al-Kahf",
    "Maryam",
    "Ta-Ha",
    "Al-Anbiya",
    "Al-Hajj",
    "Al-Mu'minun",
    "An-Nur",
    "Al-Furqan",
    "Ash-Shu'ara",
    "An-Naml",
    "Al-Qasas",
    "Al-Ankabut",
    "Ar-Rum",
    "Luqman",
    "As-Sajda",
    "Al-Ahzab",
    "Saba",
    "Fatir",
    "Ya-Sin",
    "As-Saffat",
    "Sad",
    "Az-Zumar",
    "Ghafir",
    "Fussilat",
    "Ash-Shura",
    "Az-Zukhruf",
    "Ad-Dukhan",
    "Al-Jathiya",
    "Al-Ahqaf",
    "Muhammad",
    "Al-Fath",
    "Al-Hujurat",
    "Qaf",
    "Adh-Dhariyat",
    "At-Tur",
    "An-Najm",
    "Al-Qamar",
    "Ar-Rahman",
    "Al-Waqi'a",
    "Al-Hadid",
    "Al-Mujadila",
    "Al-Hashr",
    "Al-Mumtahina",
    "As-Saff",
    "Al-Jumu'a",
    "Al-Munafiqun",
    "At-Taghabun",
    "At-Talaq",
    "At-Tahrim",
    "Al-Mulk",
    "Al-Qalam",
    "Al-Haqqah",
    "Al-Ma'arij",
    "Nuh",
    "Al-Jinn",
    "Al-Muzzammil",
    "Al-Muddathir",
    "Al-Qiyamah",
    "Al-Insan",
    "Al-Mursalat",
    "An-Naba'",
    "An-Nazi'at",
    "Abasa",
    "At-Takwir",
    "Al-Infitar",
    "Al-Mutaffifin",
    "Al-Inshiqaq",
    "Al-Buruj",
    "At-Tariq",
    "Al-A'la",
    "Al-Ghashiyah",
    "Al-Fajr",
    "Al-Balad",
    "Ash-Shams",
    "Al-Lail",
    "Ad-Duha",
    "Ash-Sharh",
    "At-Tin",
    "Al-Alaq",
    "Al-Qadr",
    "Al-Bayyina",
    "Az-Zalzalah",
    "Al-Adiyat",
    "Al-Qari'a",
    "At-Takathur",
    "Al-Asr",
    "Al-Humazah",
    "Al-Fil",
    "Quraysh",
    "Al-Ma'un",
    "Al-Kawthar",
    "Al-Kafirun",
    "An-Nasr",
    "Al-Masad",
    "Al-Ikhlas",
    "Al-Falaq",
    "An-Nas",
  ];
  List<String> ayaNumbers = [
    '7',
    '286',
    '200',
    '176',
    '120',
    '165',
    '206',
    '75',
    '129',
    '109',
    '123',
    '111',
    '43',
    '52',
    '99',
    '128',
    '111',
    '110',
    '98',
    '135',
    '112',
    '78',
    '118',
    '64',
    '77',
    '227',
    '93',
    '88',
    '69',
    '60',
    '34',
    '30',
    '73',
    '54',
    '45',
    '83',
    '182',
    '88',
    '75',
    '85',
    '54',
    '53',
    '89',
    '59',
    '37',
    '35',
    '38',
    '29',
    '18',
    '45',
    '60',
    '49',
    '62',
    '55',
    '78',
    '96',
    '29',
    '22',
    '24',
    '13',
    '14',
    '11',
    '11',
    '18',
    '12',
    '12',
    '30',
    '52',
    '52',
    '44',
    '28',
    '28',
    '20',
    '56',
    '40',
    '31',
    '50',
    '40',
    '46',
    '42',
    '29',
    '19',
    '36',
    '25',
    '22',
    '17',
    '19',
    '26',
    '30',
    '20',
    '15',
    '21',
    '11',
    '8',
    '5',
    '19',
    '5',
    '8',
    '8',
    '11',
    '11',
    '8',
    '3',
    '9',
    '5',
    '4',
    '6',
    '3',
    '6',
    '3',
    '5',
    '4',
    '5',
    '6',
  ];
  static List<SuraDataModel> suraDataLists = [
    SuraDataModel(
      suraId: "1",
      suraNameAr: "الفاتحه",
      suraNameEn: "Al-Fatiha",
      suraVersesNumber: "7",
    ),
    SuraDataModel(
      suraId: "2",
      suraNameAr: "البقرة",
      suraNameEn: "Al-Baqarah",
      suraVersesNumber: "286",
    ),
    SuraDataModel(
      suraId: "3",
      suraNameAr: "آل عمران",
      suraNameEn: "Aal-E-Imran",
      suraVersesNumber: "200",
    ),
    SuraDataModel(
      suraId: "4",
      suraNameAr: "النساء",
      suraNameEn: "An-Nisa'",
      suraVersesNumber: "176",
    ),
    SuraDataModel(
      suraId: "5",
      suraNameAr: "المائدة",
      suraNameEn: "Al-Ma'idah",
      suraVersesNumber: "120",
    ),
    SuraDataModel(
      suraId: "6",
      suraNameAr: "الأنعام",
      suraNameEn: "Al-An'am",
      suraVersesNumber: "165",
    ),
    SuraDataModel(
      suraId: "7",
      suraNameAr: "الأعراف",
      suraNameEn: "Al-A'raf",
      suraVersesNumber: "206",
    ),
    SuraDataModel(
      suraId: "8",
      suraNameAr: "الأنفال",
      suraNameEn: "Al-Anfal",
      suraVersesNumber: "75",
    ),
    SuraDataModel(
      suraId: "9",
      suraNameAr: "التوبة",
      suraNameEn: "At-Tawbah",
      suraVersesNumber: "129",
    ),
    SuraDataModel(
      suraId: "10",
      suraNameAr: "يونس",
      suraNameEn: "Yunus",
      suraVersesNumber: "109",
    ),
    SuraDataModel(
      suraId: "11",
      suraNameAr: "هود",
      suraNameEn: "Hud",
      suraVersesNumber: "123",
    ),
    SuraDataModel(
      suraId: "12",
      suraNameAr: "يوسف",
      suraNameEn: "Yusuf",
      suraVersesNumber: "111",
    ),
    SuraDataModel(
      suraId: "13",
      suraNameAr: "الرعد",
      suraNameEn: "Ar-Ra'd",
      suraVersesNumber: "43",
    ),
    SuraDataModel(
      suraId: "14",
      suraNameAr: "إبراهيم",
      suraNameEn: "Ibrahim",
      suraVersesNumber: "52",
    ),
    SuraDataModel(
      suraId: "15",
      suraNameAr: "الحجر",
      suraNameEn: "Al-Hijr",
      suraVersesNumber: "99",
    ),
    SuraDataModel(
      suraId: "16",
      suraNameAr: "النحل",
      suraNameEn: "An-Nahl",
      suraVersesNumber: "128",
    ),
    SuraDataModel(
      suraId: "17",
      suraNameAr: "الإسراء",
      suraNameEn: "Al-Isra",
      suraVersesNumber: "111",
    ),
    SuraDataModel(
      suraId: "18",
      suraNameAr: "الكهف",
      suraNameEn: "Al-Kahf",
      suraVersesNumber: "110",
    ),
    SuraDataModel(
      suraId: "19",
      suraNameAr: "مريم",
      suraNameEn: "Maryam",
      suraVersesNumber: "98",
    ),
    SuraDataModel(
      suraId: "20",
      suraNameAr: "طه",
      suraNameEn: "Ta-Ha",
      suraVersesNumber: "135",
    ),
    SuraDataModel(
      suraId: "21",
      suraNameAr: "الأنبياء",
      suraNameEn: "Al-Anbiya",
      suraVersesNumber: "112",
    ),
    SuraDataModel(
      suraId: "22",
      suraNameAr: "الحج",
      suraNameEn: "Al-Hajj",
      suraVersesNumber: "78",
    ),
    SuraDataModel(
      suraId: "23",
      suraNameAr: "المؤمنون",
      suraNameEn: "Al-Mu'minun",
      suraVersesNumber: "118",
    ),
    SuraDataModel(
      suraId: "24",
      suraNameAr: "النّور",
      suraNameEn: "An-Nur",
      suraVersesNumber: "64",
    ),
    SuraDataModel(
      suraId: "25",
      suraNameAr: "الفرقان",
      suraNameEn: "Al-Furqan",
      suraVersesNumber: "77",
    ),
    SuraDataModel(
      suraId: "26",
      suraNameAr: "الشعراء",
      suraNameEn: "Ash-Shu'ara",
      suraVersesNumber: "227",
    ),
    SuraDataModel(
      suraId: "27",
      suraNameAr: "النّمل",
      suraNameEn: "An-Naml",
      suraVersesNumber: "93",
    ),
    SuraDataModel(
      suraId: "28",
      suraNameAr: "القصص",
      suraNameEn: "Al-Qasas",
      suraVersesNumber: "88",
    ),
    SuraDataModel(
      suraId: "29",
      suraNameAr: "العنكبوت",
      suraNameEn: "Al-Ankabut",
      suraVersesNumber: "69",
    ),
    SuraDataModel(
      suraId: "30",
      suraNameAr: "الرّوم",
      suraNameEn: "Ar-Rum",
      suraVersesNumber: "60",
    ),
    SuraDataModel(
      suraId: "31",
      suraNameAr: "لقمان",
      suraNameEn: "Luqman",
      suraVersesNumber: "34",
    ),
    SuraDataModel(
      suraId: "32",
      suraNameAr: "السجدة",
      suraNameEn: "As-Sajda",
      suraVersesNumber: "30",
    ),
    SuraDataModel(
      suraId: "33",
      suraNameAr: "الأحزاب",
      suraNameEn: "Al-Ahzab",
      suraVersesNumber: "73",
    ),
    SuraDataModel(
      suraId: "34",
      suraNameAr: "سبأ",
      suraNameEn: "Saba",
      suraVersesNumber: "54",
    ),
    SuraDataModel(
      suraId: "35",
      suraNameAr: "فاطر",
      suraNameEn: "Fatir",
      suraVersesNumber: "45",
    ),
    SuraDataModel(
      suraId: "36",
      suraNameAr: "يس",
      suraNameEn: "Ya-Sin",
      suraVersesNumber: "83",
    ),
    SuraDataModel(
      suraId: "37",
      suraNameAr: "الصافات",
      suraNameEn: "As-Saffat",
      suraVersesNumber: "182",
    ),
    SuraDataModel(
      suraId: "38",
      suraNameAr: "ص",
      suraNameEn: "Sad",
      suraVersesNumber: "88",
    ),
    SuraDataModel(
      suraId: "39",
      suraNameAr: "الزمر",
      suraNameEn: "Az-Zumar",
      suraVersesNumber: "75",
    ),
    SuraDataModel(
      suraId: "40",
      suraNameAr: "غافر",
      suraNameEn: "Ghafir",
      suraVersesNumber: "85",
    ),
    SuraDataModel(
      suraId: "41",
      suraNameAr: "فصّلت",
      suraNameEn: "Fussilat",
      suraVersesNumber: "54",
    ),
    SuraDataModel(
      suraId: "42",
      suraNameAr: "الشورى",
      suraNameEn: "Ash-Shura",
      suraVersesNumber: "53",
    ),
    SuraDataModel(
      suraId: "43",
      suraNameAr: "الزخرف",
      suraNameEn: "Az-Zukhruf",
      suraVersesNumber: "89",
    ),
    SuraDataModel(
      suraId: "44",
      suraNameAr: "الدّخان",
      suraNameEn: "Ad-Dukhan",
      suraVersesNumber: "59",
    ),
    SuraDataModel(
      suraId: "45",
      suraNameAr: "الجاثية",
      suraNameEn: "Al-Jathiya",
      suraVersesNumber: "37",
    ),
    SuraDataModel(
      suraId: "46",
      suraNameAr: "الأحقاف",
      suraNameEn: "Al-Ahqaf",
      suraVersesNumber: "35",
    ),
    SuraDataModel(
      suraId: "47",
      suraNameAr: "محمد",
      suraNameEn: "Muhammad",
      suraVersesNumber: "38",
    ),
    SuraDataModel(
      suraId: "48",
      suraNameAr: "الفتح",
      suraNameEn: "Al-Fath",
      suraVersesNumber: "29",
    ),
    SuraDataModel(
      suraId: "49",
      suraNameAr: "الحجرات",
      suraNameEn: "Al-Hujurat",
      suraVersesNumber: "18",
    ),
    SuraDataModel(
      suraId: "50",
      suraNameAr: "ق",
      suraNameEn: "Qaf",
      suraVersesNumber: "45",
    ),
    SuraDataModel(
      suraId: "51",
      suraNameAr: "الذاريات",
      suraNameEn: "Adh-Dhariyat",
      suraVersesNumber: "60",
    ),
    SuraDataModel(
      suraId: "52",
      suraNameAr: "الطور",
      suraNameEn: "At-Tur",
      suraVersesNumber: "49",
    ),
    SuraDataModel(
      suraId: "53",
      suraNameAr: "النجم",
      suraNameEn: "An-Najm",
      suraVersesNumber: "62",
    ),
    SuraDataModel(
      suraId: "54",
      suraNameAr: "القمر",
      suraNameEn: "Al-Qamar",
      suraVersesNumber: "55",
    ),
    SuraDataModel(
      suraId: "55",
      suraNameAr: "الرحمن",
      suraNameEn: "Ar-Rahman",
      suraVersesNumber: "78",
    ),
    SuraDataModel(
      suraId: "56",
      suraNameAr: "الواقعة",
      suraNameEn: "Al-Waqi'a",
      suraVersesNumber: "96",
    ),
    SuraDataModel(
      suraId: "57",
      suraNameAr: "الحديد",
      suraNameEn: "Al-Hadid",
      suraVersesNumber: "29",
    ),
    SuraDataModel(
      suraId: "58",
      suraNameAr: "المجادلة",
      suraNameEn: "Al-Mujadila",
      suraVersesNumber: "22",
    ),
    SuraDataModel(
      suraId: "59",
      suraNameAr: "الحشر",
      suraNameEn: "Al-Hashr",
      suraVersesNumber: "24",
    ),
    SuraDataModel(
      suraId: "60",
      suraNameAr: "الممتحنة",
      suraNameEn: "Al-Mumtahina",
      suraVersesNumber: "13",
    ),
    SuraDataModel(
      suraId: "61",
      suraNameAr: "الصف",
      suraNameEn: "As-Saff",
      suraVersesNumber: "14",
    ),
    SuraDataModel(
      suraId: "62",
      suraNameAr: "الجمعة",
      suraNameEn: "Al-Jumu'a",
      suraVersesNumber: "11",
    ),
    SuraDataModel(
      suraId: "63",
      suraNameAr: "المنافقون",
      suraNameEn: "Al-Munafiqun",
      suraVersesNumber: "11",
    ),
    SuraDataModel(
      suraId: "64",
      suraNameAr: "التغابن",
      suraNameEn: "At-Taghabun",
      suraVersesNumber: "18",
    ),
    SuraDataModel(
      suraId: "65",
      suraNameAr: "الطلاق",
      suraNameEn: "At-Talaq",
      suraVersesNumber: "12",
    ),
    SuraDataModel(
      suraId: "66",
      suraNameAr: "التحريم",
      suraNameEn: "At-Tahrim",
      suraVersesNumber: "12",
    ),
    SuraDataModel(
      suraId: "67",
      suraNameAr: "الملك",
      suraNameEn: "Al-Mulk",
      suraVersesNumber: "30",
    ),
    SuraDataModel(
      suraId: "68",
      suraNameAr: "القلم",
      suraNameEn: "Al-Qalam",
      suraVersesNumber: "52",
    ),
    SuraDataModel(
      suraId: "69",
      suraNameAr: "الحاقة",
      suraNameEn: "Al-Haqqah",
      suraVersesNumber: "52",
    ),
    SuraDataModel(
      suraId: "70",
      suraNameAr: "المعارج",
      suraNameEn: "Al-Ma'arij",
      suraVersesNumber: "44",
    ),
    SuraDataModel(
      suraId: "71",
      suraNameAr: "نوح",
      suraNameEn: "Nuh",
      suraVersesNumber: "28",
    ),
    SuraDataModel(
      suraId: "72",
      suraNameAr: "الجن",
      suraNameEn: "Al-Jinn",
      suraVersesNumber: "28",
    ),
    SuraDataModel(
      suraId: "73",
      suraNameAr: "المزّمّل",
      suraNameEn: "Al-Muzzammil",
      suraVersesNumber: "20",
    ),
    SuraDataModel(
      suraId: "74",
      suraNameAr: "المدّثر",
      suraNameEn: "Al-Muddathir",
      suraVersesNumber: "56",
    ),
    SuraDataModel(
      suraId: "75",
      suraNameAr: "القيامة",
      suraNameEn: "Al-Qiyamah",
      suraVersesNumber: "40",
    ),
    SuraDataModel(
      suraId: "76",
      suraNameAr: "الإنسان",
      suraNameEn: "Al-Insan",
      suraVersesNumber: "31",
    ),
    SuraDataModel(
      suraId: "77",
      suraNameAr: "المرسلات",
      suraNameEn: "Al-Mursalat",
      suraVersesNumber: "50",
    ),
    SuraDataModel(
      suraId: "78",
      suraNameAr: "النبأ",
      suraNameEn: "An-Naba'",
      suraVersesNumber: "40",
    ),
    SuraDataModel(
      suraId: "79",
      suraNameAr: "النازعات",
      suraNameEn: "An-Nazi'at",
      suraVersesNumber: "46",
    ),
    SuraDataModel(
      suraId: "80",
      suraNameAr: "عبس",
      suraNameEn: "Abasa",
      suraVersesNumber: "42",
    ),
    SuraDataModel(
      suraId: "81",
      suraNameAr: "التكوير",
      suraNameEn: "At-Takwir",
      suraVersesNumber: "29",
    ),
    SuraDataModel(
      suraId: "82",
      suraNameAr: "الإنفطار",
      suraNameEn: "Al-Infitar",
      suraVersesNumber: "19",
    ),
    SuraDataModel(
      suraId: "83",
      suraNameAr: "المطفّفين",
      suraNameEn: "Al-Mutaffifin",
      suraVersesNumber: "36",
    ),
    SuraDataModel(
      suraId: "84",
      suraNameAr: "الإنشقاق",
      suraNameEn: "Al-Inshiqaq",
      suraVersesNumber: "25",
    ),
    SuraDataModel(
      suraId: "85",
      suraNameAr: "البروج",
      suraNameEn: "Al-Buruj",
      suraVersesNumber: "22",
    ),
    SuraDataModel(
      suraId: "86",
      suraNameAr: "الطارق",
      suraNameEn: "At-Tariq",
      suraVersesNumber: "17",
    ),
    SuraDataModel(
      suraId: "87",
      suraNameAr: "الأعلى",
      suraNameEn: "Al-A'la",
      suraVersesNumber: "19",
    ),
    SuraDataModel(
      suraId: "88",
      suraNameAr: "الغاشية",
      suraNameEn: "Al-Ghashiyah",
      suraVersesNumber: "26",
    ),
    SuraDataModel(
      suraId: "89",
      suraNameAr: "الفجر",
      suraNameEn: "Al-Fajr",
      suraVersesNumber: "30",
    ),
    SuraDataModel(
      suraId: "90",
      suraNameAr: "البلد",
      suraNameEn: "Al-Balad",
      suraVersesNumber: "20",
    ),
    SuraDataModel(
      suraId: "91",
      suraNameAr: "الشمس",
      suraNameEn: "Ash-Shams",
      suraVersesNumber: "15",
    ),
    SuraDataModel(
      suraId: "92",
      suraNameAr: "الليل",
      suraNameEn: "Al-Lail",
      suraVersesNumber: "21",
    ),
    SuraDataModel(
      suraId: "93",
      suraNameAr: "الضحى",
      suraNameEn: "Ad-Duha",
      suraVersesNumber: "11",
    ),
    SuraDataModel(
      suraId: "94",
      suraNameAr: "الشرح",
      suraNameEn: "Ash-Sharh",
      suraVersesNumber: "8",
    ),
    SuraDataModel(
      suraId: "95",
      suraNameAr: "التين",
      suraNameEn: "At-Tin",
      suraVersesNumber: "8",
    ),
    SuraDataModel(
      suraId: "96",
      suraNameAr: "العلق",
      suraNameEn: "Al-Alaq",
      suraVersesNumber: "19",
    ),
    SuraDataModel(
      suraId: "97",
      suraNameAr: "القدر",
      suraNameEn: "Al-Qadr",
      suraVersesNumber: "5",
    ),
    SuraDataModel(
      suraId: "98",
      suraNameAr: "البينة",
      suraNameEn: "Al-Bayyina",
      suraVersesNumber: "8",
    ),
    SuraDataModel(
      suraId: "99",
      suraNameAr: "الزلزلة",
      suraNameEn: "Az-Zalzalah",
      suraVersesNumber: "8",
    ),
    SuraDataModel(
      suraId: "100",
      suraNameAr: "العاديات",
      suraNameEn: "Al-Adiyat",
      suraVersesNumber: "11",
    ),
    SuraDataModel(
      suraId: "101",
      suraNameAr: "القارعة",
      suraNameEn: "Al-Qari'a",
      suraVersesNumber: "11",
    ),
    SuraDataModel(
      suraId: "102",
      suraNameAr: "التكاثر",
      suraNameEn: "At-Takathur",
      suraVersesNumber: "8",
    ),
    SuraDataModel(
      suraId: "103",
      suraNameAr: "العصر",
      suraNameEn: "Al-Asr",
      suraVersesNumber: "3",
    ),
    SuraDataModel(
      suraId: "104",
      suraNameAr: "الهمزة",
      suraNameEn: "Al-Humazah",
      suraVersesNumber: "9",
    ),
    SuraDataModel(
      suraId: "105",
      suraNameAr: "الفيل",
      suraNameEn: "Al-Fil",
      suraVersesNumber: "5",
    ),
    SuraDataModel(
      suraId: "106",
      suraNameAr: "قريش",
      suraNameEn: "Quraysh",
      suraVersesNumber: "4",
    ),
    SuraDataModel(
      suraId: "107",
      suraNameAr: "الماعون",
      suraNameEn: "Al-Ma'un",
      suraVersesNumber: "7",
    ),
    SuraDataModel(
      suraId: "108",
      suraNameAr: "الكوثر",
      suraNameEn: "Al-Kawthar",
      suraVersesNumber: "3",
    ),
    SuraDataModel(
      suraId: "109",
      suraNameAr: "الكافرون",
      suraNameEn: "Al-Kafirun",
      suraVersesNumber: "6",
    ),
    SuraDataModel(
      suraId: "110",
      suraNameAr: "النصر",
      suraNameEn: "An-Nasr",
      suraVersesNumber: "3",
    ),
    SuraDataModel(
      suraId: "111",
      suraNameAr: "المسد",
      suraNameEn: "Al-Masad",
      suraVersesNumber: "5",
    ),
    SuraDataModel(
      suraId: "112",
      suraNameAr: "الإخلاص",
      suraNameEn: "Al-Ikhlas",
      suraVersesNumber: "4",
    ),
    SuraDataModel(
      suraId: "113",
      suraNameAr: "الفلق",
      suraNameEn: "Al-Falaq",
      suraVersesNumber: "5",
    ),
    SuraDataModel(
      suraId: "114",
      suraNameAr: "الناس",
      suraNameEn: "An-Nas",
      suraVersesNumber: "6",
    ),
  ];
}
